import {test} from 'node:test';import assert from 'node:assert/strict';import {repositorySetup} from '../server/repository-setup';import {readFile} from 'node:fs/promises';
const key='synthetic-only-token-123456';const origin='https://counterchime.example';
const req=(body:unknown={apiKey:key},headers:Record<string,string>={},method='POST')=>new Request(`${origin}/api/setup-repository`,{method,headers:{origin,'Content-Type':'application/json',...headers},...(method==='POST'?{body:JSON.stringify(body)}:{})});
const repo={full_name:'uni-native/counterchime',private:false,html_url:'https://github.com/uni-native/counterchime'};
async function mock(responses:Response[],run:(calls:{url:string;init?:RequestInit}[])=>Promise<void>){const old=globalThis.fetch;const calls:{url:string;init?:RequestInit}[]=[];globalThis.fetch=async(input,init)=>{calls.push({url:String(input),init});const r=responses.shift();if(!r)throw Error(key);return r;};try{await run(calls);}finally{globalThis.fetch=old;}}
const j=(x:unknown,status=200)=>Response.json(x,{status});
test('repository setup fails closed for method, origin and malformed body',async()=>{await mock([],async calls=>{assert.equal((await repositorySetup(req({}, {},'GET'))).status,405);assert.equal((await repositorySetup(req(undefined,{origin:'https://other.example'}))).status,403);assert.equal((await repositorySetup(req({apiKey:key,url:'https://evil.example'}))).status,400);assert.equal((await repositorySetup(req({apiKey:'x'.repeat(3000)}))).status,400);assert.equal(calls.length,0);});});
test('wrong account cannot create a repository',async()=>{await mock([j({login:'other'})],async calls=>{assert.equal((await repositorySetup(req())).status,403);assert.equal(calls.length,1);});});
test('existing public repository is returned unchanged',async()=>{await mock([j({login:'uni-native'}),j(repo)],async calls=>{assert.deepEqual(await(await repositorySetup(req())).json(),{url:repo.html_url,created:false});assert.equal(calls.length,2);assert.ok(calls.every(c=>c.init?.method==='GET'));});});
test('fixed public empty repository creation validates exact result',async()=>{await mock([j({login:'uni-native'}),j({},404),j(repo,201)],async calls=>{assert.equal((await repositorySetup(req())).status,200);assert.deepEqual(calls.map(c=>c.url),['https://api.github.com/user','https://api.github.com/repos/uni-native/counterchime','https://api.github.com/user/repos']);const body=JSON.parse(calls[2].init!.body as string);assert.equal(body.name,'counterchime');assert.equal(body.private,false);assert.equal(body.auto_init,false);assert.ok(calls.every(c=>c.init?.redirect==='error'));});});
test('private existing repository is never made public',async()=>{await mock([j({login:'uni-native'}),j({...repo,private:true})],async calls=>{assert.equal((await repositorySetup(req())).status,409);assert.equal(calls.length,2);});});
test('upstream secret reflection and errors are redacted',async()=>{await mock([j({message:key},401)],async()=>{assert.ok(!(await(await repositorySetup(req())).text()).includes(key));});await mock([],async()=>{assert.ok(!(await(await repositorySetup(req())).text()).includes(key));});});
test('unexpected destination never appears in successful output',async()=>{await mock([j({login:'uni-native'}),j({...repo,html_url:'https://evil.example/'+key})],async()=>{const result=await repositorySetup(req());assert.equal(result.status,409);assert.ok(!(await result.text()).includes(key));});});
test('retired setup page accepts no credentials',async()=>{const html=await readFile('public/repository-setup.html','utf8');assert.doesNotMatch(html,/<input|<form|repository-setup.js/);});
test('sanitized failures distinguish account rejection, creation permission and validation',async()=>{for(const status of [401,403,422]){await mock(status===401?[j({secret:key},401)]:[j({login:'uni-native'}),j({},404),j({secret:key},status)],async()=>{const r=await repositorySetup(req());const body=await r.json();assert.equal(body.upstreamStatus,status);assert.equal(body.stage,status===401?'account':'create');assert.equal(body.code,status===401?'TOKEN_REJECTED':status===403?'PERMISSION':'VALIDATION');assert.ok(!JSON.stringify(body).includes(key));});}});

 test('production setup route is inert',async()=>{const {api}=await import('../server/api');assert.equal((await api(req(),{}))?.status,410);});
