import {Fragment} from 'react';
import type {Inventory} from '../engine';
import type {Receipt} from '../session';
import {RESOURCES,formatInventory} from '../scenarios';
import {Icon} from './Icon';
function Token({kind}:{kind:string}){return <svg className={`token token-${kind}`} viewBox="0 0 48 48" aria-hidden="true">{kind==='wood'?<><path d="M12 34 29 7c4-6 16 1 13 7L25 41c-4 6-17-1-13-7Z"/><ellipse cx="18.5" cy="37" rx="8" ry="6" transform="rotate(32 18.5 37)"/><path d="m22 28 13-19M27 31l12-19M16 37q4-5 7 1"/></>:kind==='stone'?<><path d="m6 30 7-20 16-5 13 13-3 21-21 5Z"/><path d="m6 30 16 3 7-28M22 33l17 6"/></>:<path d="m24 4 6 13 14 2-10 10 3 15-13-7-13 7 3-15L4 19l14-2Z"/>}</svg>;}
function InventoryGlyph({inventory}:{inventory:Inventory}) {return <div className="inventory-glyph"><div className="token-group">{RESOURCES.flatMap(r=>Array.from({length:Math.min(inventory[r],4)},(_,i)=><Token key={`${r}-${i}`} kind={r}/>))}</div><strong>{formatInventory(inventory)}</strong></div>;}
export function Evidence({receipt,revision,replayStep,onReplay,onSelectStep,playing}:{receipt:Receipt|null;revision:number;replayStep:number;onReplay:()=>void;onSelectStep:(n:number)=>void;playing:boolean}) {
 const current=receipt?.revision===revision;const result=receipt?.result;const found=result?.status==='found';const steps=result?.steps || [];const states=receipt?[receipt.scenario.initial,...steps.map(s=>s.after)]:[];
 return <section className={`evidence ${!current&&receipt?'outdated':''}`} aria-labelledby="evidence-heading"><div className="section-heading"><h2 id="evidence-heading"><span>02 /</span> Counterexample</h2>{receipt&&<span className={`result-label ${found&&current?'found':''}`}>{!current?'Outdated · test again':found?'Growth loop found':result?.status==='limit'?'Search limit reached':'No growth loop found'}</span>}</div>
 {!receipt?<div className="empty-evidence"><span className="empty-mark">↻</span><h3>Put your rules to the test</h3><p>A growth loop returns everything it started with, plus at least one extra resource. The checker will look for an exact, replayable witness.</p></div>:found?<>
 <div className="witness-visual" aria-label="Growth loop inventory sequence">{states.length<=4?states.map((state,i)=><Fragment key={i}>{i>0&&<span className="sequence-arrow" aria-hidden="true">→</span>}<button className={`state-node ${replayStep===i?'active':''}`} onClick={()=>onSelectStep(i)} aria-label={`Show step ${i}: ${formatInventory(state)}`} aria-pressed={replayStep===i}><InventoryGlyph inventory={state}/></button></Fragment>):<><InventoryGlyph inventory={states[result!.cycleStart||0]}/><span className="sequence-arrow">→ <small>{steps.length-(result!.cycleStart||0)} trades</small> →</span><InventoryGlyph inventory={states.at(-1)!}/></>}</div>
 <p className="cycle-gain">{RESOURCES.filter(r=>result!.gain![r]>0).map(r=>`+${result!.gain![r]} ${r}`).join(' · ')} per cycle</p>
 <p className="witness-proof"><Icon name="check" size={16}/>{receipt.verified?'Independently replay-verified':'Unverified'}<span>·</span> {result!.cycleStart ? `${result!.cycleStart} setup trade(s), then a repeatable loop`:'Starting resources fully recovered'}</p>
 <div className="replay-heading"><h3>Rule replay</h3><button className="button accent" onClick={onReplay} disabled={!current}><Icon name={playing?'stop':'play'} size={15}/>{playing?'Pause replay':'Replay counterexample'}</button></div>
 <div className="replay-table-wrap"><table className="replay-table"><caption className="sr-only">Exact inventory after each trade. Choose a step to inspect it.</caption><thead><tr><th>Step</th><th>Trade</th>{RESOURCES.map(r=><th key={r}>{r}</th>)}</tr></thead><tbody><tr className={replayStep===0?'selected':''} onClick={()=>onSelectStep(0)}><td><button className="step-button" onClick={()=>onSelectStep(0)} aria-pressed={replayStep===0} aria-label="Show starting inventory">Start</button></td><td>Initial inventory</td>{RESOURCES.map(r=><td key={r}>{receipt.scenario.initial[r]}</td>)}</tr>{steps.map((step,i)=>{const rule=receipt.scenario.rules.find(r=>r.id===step.ruleId)!;return <tr key={i} className={replayStep===i+1?'selected':''} onClick={()=>onSelectStep(i+1)}><td><button className="step-button" onClick={()=>onSelectStep(i+1)} aria-pressed={replayStep===i+1} aria-label={`Show replay step ${i+1}`}>{String(i+1).padStart(2,'0')}{i===result!.cycleStart&&<span className="loop-marker" title="Loop begins here">↻</span>}</button></td><td>{formatInventory(rule.input)} <span className="muted">→</span> {formatInventory(rule.output)}</td>{RESOURCES.map(r=><td key={r}>{step.after[r]}</td>)}</tr>;})}</tbody></table></div>
 <div className="replay-scrubber"><input type="range" min="0" max={steps.length} value={replayStep} onChange={e=>onSelectStep(Number(e.target.value))} aria-label="Replay step"/><span>Step {replayStep} / {steps.length}</span></div>
 </>:<div className="negative-result"><div className="neutral-mark">↔</div><h3>No growth loop found<br/>within these limits</h3><p>Checked up to {result!.limits.maxDepth} trades with quantities up to {result!.limits.resourceCap} per resource and a {result!.limits.maxStates.toLocaleString()}-state budget.</p>{result!.hitLimits.length>0&&<p className="limit-warning">Search was truncated by: {result!.hitLimits.join(', ')}.</p>}<p className="not-proof">This is not a proof of balance. A longer or different path may still produce growth.</p></div>}
 {receipt&&<div className="receipt-meta" aria-live="polite"><span>Rulebook v{receipt.revision}</span><span>{result!.explored.toLocaleString()} states explored</span><span>{receipt.elapsedMs.toFixed(1)} ms</span>{current&&<span>Local deterministic checker</span>}</div>}
 </section>;
}
