import {freshRuleId} from '../rule-id';
import {useState} from 'react';
import type {Inventory,Rule,Scenario,Resource} from '../engine';
import {EXAMPLES,RESOURCES,formatInventory,zero} from '../scenarios';
import {Icon} from './Icon';
function Side({value,onChange,label}:{value:Inventory;onChange:(v:Inventory)=>void;label:string}) {
 const nonzero=RESOURCES.filter(r=>value[r]>0);const selected=nonzero[0] || 'wood';
 const [expanded,setExpanded]=useState(false);
 if(expanded || nonzero.length>1) return <div className="vector-editor">{RESOURCES.map(r=><label key={r}><span>{r}</span><input type="number" min="0" max="9" aria-label={`${label} ${r}`} value={value[r]} onChange={e=>onChange({...value,[r]:Number(e.target.value)})}/></label>)}{nonzero.length<=1&&<button className="text-button" onClick={()=>setExpanded(false)}>Compact</button>}</div>;
 return <div className="rule-side"><input type="number" min="1" max="9" aria-label={`${label} quantity`} value={value[selected]} onChange={e=>onChange({...zero(),[selected]:Number(e.target.value)})}/><select aria-label={`${label} resource`} value={selected} onChange={e=>onChange({...zero(),[e.target.value]:value[selected]})}>{RESOURCES.map(r=><option key={r}>{r}</option>)}</select><button className="mix-button" onClick={()=>setExpanded(true)} title="Use multiple resources" aria-label={`${label}: use multiple resources`}>+</button></div>;
}
export function Rulebook({scenario,revision,latestEdit,onChange,onExample,onRun,onUndo,canUndo,busy}:{scenario:Scenario;revision:number;latestEdit:string|null;onChange:(s:Scenario,id?:string)=>void;onExample:(id:string)=>void;onRun:()=>void;onUndo:()=>void;canUndo:boolean;busy:boolean}) {
 const updateRule=(index:number,key:'input'|'output',value:Inventory)=>{const rules=[...scenario.rules];rules[index]={...rules[index],[key]:value};onChange({...scenario,rules},rules[index].id);};
 const add=()=>{const rule:Rule={id:freshRuleId(scenario.rules,revision+1,scenario.rules.length+1),name:`Trade ${scenario.rules.length+1}`,input:{wood:1,stone:0,stars:0},output:{wood:0,stone:1,stars:0}};onChange({...scenario,rules:[...scenario.rules,rule]},rule.id);};
 return <section className="rulebook" aria-labelledby="rulebook-heading"><div className="section-heading"><h2 id="rulebook-heading"><span>01 /</span> Rulebook</h2><span className="revision">v{revision}</span></div>
 <label className="scenario-picker"><span>Economy</span><select value={EXAMPLES.find(x=>x.scenario.title===scenario.title)?.id || ''} onChange={e=>onExample(e.target.value)} aria-label="Example economy"><option value="" disabled>Custom economy</option>{EXAMPLES.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
 <h3>Initial inventory</h3><div className="initial-inventory">{RESOURCES.map((r:Resource)=><label key={r}><span>{r}</span><input type="number" min="0" max="9" value={scenario.initial[r]} aria-label={`Initial ${r}`} onChange={e=>onChange({...scenario,initial:{...scenario.initial,[r]:Number(e.target.value)}})}/></label>)}</div>
 <div className="trade-label"><h3>Trade rules</h3><span>{scenario.rules.length} / 6</span></div><div className="trade-list">{scenario.rules.map((rule,i)=><div key={rule.id} className={`trade-row ${latestEdit===rule.id?'edited':''}`}><span className="rule-number" title={rule.name}>{i+1}</span><div className="trade-edit"><Side value={rule.input} onChange={v=>updateRule(i,'input',v)} label={`Rule ${i+1} input`}/><span className="trade-arrow" aria-label="produces">→</span><Side value={rule.output} onChange={v=>updateRule(i,'output',v)} label={`Rule ${i+1} output`}/></div><button className="icon-button remove-rule" aria-label={`Remove rule ${i+1}: ${formatInventory(rule.input)} to ${formatInventory(rule.output)}`} onClick={()=>onChange({...scenario,rules:scenario.rules.filter((_,j)=>i!==j)})}><Icon name="trash" size={16}/></button></div>)}</div>
 <button className="button add-rule" onClick={add} disabled={scenario.rules.length>=6}><Icon name="plus"/>Add rule</button>
 <div className="rule-actions"><button className="button primary" onClick={onRun} disabled={busy}><Icon name="play" size={16}/>{busy?'Checking…':'Test economy'}</button><button className="button undo" title="Undo last edit" aria-label="Undo last edit" onClick={onUndo} disabled={!canUndo}><Icon name="undo"/></button></div>
 <p className="limits">8 trades · 10,000 states · 30 units / resource</p>
 <details className="assumptions"><summary>What this model includes</summary><p>Unlimited deterministic trades. Three resources, integer quantities, no hidden conditions, randomness, storage caps, cooldowns, or turn costs. The unit ceiling limits the search, not the game.</p><p>Every rule must consume and produce at least one resource. A negative search result is not a proof of balance.</p></details></section>;
}
