import {chromium} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.goto('http://localhost:5173',{waitUntil:'networkidle'});
await page.getByRole('heading',{name:'Find the loop. Fix the rules.'}).waitFor();
await page.getByText('+1 wood per cycle',{exact:true}).waitFor();
await page.screenshot({path:'qa-artifacts/desktop-growth.png',fullPage:true});
await page.getByPlaceholder('Change the second rule to two wood').fill('Change the second rule to two wood');
await page.getByRole('button',{name:'Apply',exact:true}).click();
await page.getByRole('heading',{name:'No growth loop found within these limits'}).waitFor();
await page.screenshot({path:'qa-artifacts/desktop-repaired.png',fullPage:true});
await page.getByRole('button',{name:'Undo last edit',exact:true}).click();
await page.getByText('+1 wood per cycle',{exact:true}).waitFor();
await page.getByLabel('Rule 2 output quantity',{exact:true}).fill('4');
await page.getByText('Outdated · test again',{exact:true}).waitFor();
await page.getByRole('button',{name:'Test economy',exact:true}).click();
await page.getByText('+2 wood per cycle',{exact:true}).waitFor();
await page.getByLabel('Example economy').selectOption('locked');
await page.getByRole('heading',{name:'No growth loop found within these limits'}).waitFor();
await page.getByLabel('Example economy').selectOption('three');
await page.getByText('+1 wood per cycle',{exact:true}).waitFor();
await page.getByRole('button',{name:'Replay counterexample'}).click();
await page.getByText('Step 3 / 3',{exact:true}).waitFor();
await page.getByLabel('Example economy').selectOption('timber');
const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export session'}).click();const download=await downloadPromise;await download.saveAs('qa-artifacts/verified-session.json');
const disabled=await page.getByRole('button',{name:'Start voice session'}).isDisabled();
if(!disabled)throw new Error('Live voice must be disabled without server credentials');
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'qa-artifacts/mobile-growth.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
if(overflow)throw new Error('Mobile layout overflows');
await page.reload();await page.getByText('+1 wood per cycle',{exact:true}).waitFor();
await writeFile('qa-artifacts/ui-report.json',JSON.stringify({date:new Date().toISOString(),url:page.url(),title:await page.title(),viewports:[[1440,1000],[390,844]],checks:['initial growth','local repair','undo','stale evidence','retest','unreachable loop','three-resource loop','replay','export','disabled live voice','mobile no overflow','reload persistence'],errors},null,2));
await browser.close();if(errors.length)throw new Error(errors.join('\n'));console.log('UI smoke checks passed');
